stages:
- name: Build & Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: bots-ffl-west:${CICD_EXECUTION_SEQUENCE}
    env:
      PLUGIN_MTU: "1450"
  when:
    event:
      include:
      - push
      - pull_request
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./west-dc.yaml
  when:
    event:
      include:
      - push
      - pull_request
branch:
  include:
  - main
notification: {}
