apiVersion: apps/v1
kind: Deployment
metadata:
  name: west
  namespace: botsffl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: west
  template:
    metadata:
      labels:
        app: west
    spec:
      containers:
      - name: west
        image: registry:5000/botsffl:west
        imagePullPolicy: Always
        env:
        - name: WEST
          valueFrom:
            configMapKeyRef:
              key: WEST
              name: botsffl-league-ids
        - name: USER_ID
          valueFrom:
            configMapKeyRef:
              key: USER_ID
              name: botsffl-league-ids
        - name: CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              key: CONSUMER_KEY
              name: ffl-twitter-account
        - name: CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              key: CONSUMER_SECRET
              name: ffl-twitter-account
        - name: KEY
          valueFrom:
            secretKeyRef:
              key: KEY
              name: ffl-twitter-account
        - name: SECRET
          valueFrom:
            secretKeyRef:
              key: SECRET
              name: ffl-twitter-account
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              key: REDIS_PASS
              name: redis-pass
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              key: REDIS_HOST
              name: redis-pass